Repository traPtitech/Jomon-UI, pull requests merged in 2024-12, with the labels that each got.

#338 chore: Node.js のバージョンを 22.11.0 に更新
  .node-version
Labels: Review effort [1-5]: 1

#298 feat/ヘルプリンクの追加
  src/components/navigation/JomonHeader.vue
Labels: Review effort [1-5]: 2

#364 🎸 feat: fetchRequest で offset limit を加えて送る
  src/features/request/model.ts
  src/features/request/repository.ts
  src/stores/request.ts
Labels: Review effort [1-5]: 2

#360 🤖 chore: フォーマット
  src/components/groupDetail/GroupName.vue
  src/components/modal/ModalWrapper.vue
  src/components/modal/StatusChangeModal.vue
  src/components/newRequest/NewRequestFileForm.vue
  src/components/newRequest/NewRequestTag.vue
  src/components/newRequest/NewRequestTargets.vue
  src/components/newTransaction/NewTransactionTarget.vue
  src/components/requestDetail/RequestTags.vue
  src/components/requestDetail/RequestTargets.vue
  src/components/shared/InputSelectMultiple.vue
  src/components/shared/InputSelectSingle.vue
  src/features/request/model.ts
  src/features/request/repository.ts
  src/pages/AdminPage.vue
  src/pages/NewGroupPage.vue
  src/stores/request.ts
Labels: Review effort [1-5]: 2

#359 💡 refactor: 見出しを順番に付ける
  src/components/groupDetail/GroupBudget.vue
  src/components/groupDetail/GroupDescription.vue
  src/components/groupDetail/GroupMembers.vue
  src/components/groupDetail/GroupName.vue
  src/components/groupDetail/GroupOwners.vue
  src/components/modal/ModalWrapper.vue
  src/components/modal/StatusChangeModal.vue
  src/components/newRequest/NewRequestFileForm.vue
  src/components/newRequest/NewRequestTag.vue
  src/components/newRequest/NewRequestTargets.vue
  src/components/newTransaction/NewTransactionTarget.vue
  src/components/requestDetail/RequestGroup.vue
  src/components/requestDetail/RequestTags.vue
  src/components/requestDetail/RequestTargets.vue
  src/components/shared/InputSelectMultiple.vue
  src/components/shared/InputSelectSingle.vue
  src/features/request/model.ts
  src/features/request/repository.ts
  src/pages/AdminPage.vue
  src/pages/NewGroupPage.vue
  src/pages/NewRequestPage.vue
  src/stores/request.ts
Labels: Review effort [1-5]: 2

#358 💡 refactor: margin ではなく gap を使うようにする
  src/components/groupDetail/GroupBudget.vue
  src/components/groupDetail/GroupDescription.vue
  src/components/groupDetail/GroupMembers.vue
  src/components/groupDetail/GroupName.vue
  src/components/groupDetail/GroupOwners.vue
  src/components/modal/ModalWrapper.vue
  src/components/modal/StatusChangeModal.vue
  src/components/newRequest/NewRequestFileForm.vue
  src/components/newRequest/NewRequestTag.vue
  src/components/newRequest/NewRequestTargets.vue
  src/components/newTransaction/NewTransactionTarget.vue
  src/components/requestDetail/RequestGroup.vue
  src/components/requestDetail/RequestTags.vue
  src/components/requestDetail/RequestTargets.vue
  src/components/requests/RequestItem.vue
  src/components/shared/InputRadioButton.vue
  src/components/shared/InputSelectMultiple.vue
  src/components/shared/InputSelectSingle.vue
  src/components/transactionDetail/EditTransactionForm.vue
  src/components/transactionDetail/TransactionDetail.vue
  src/features/request/model.ts
  src/features/request/repository.ts
  src/pages/AdminPage.vue
  src/pages/GroupDetailPage.vue
  src/pages/GroupsPage.vue
  src/pages/NewGroupPage.vue
  src/pages/NewRequestPage.vue
  src/pages/RequestsPage.vue
  src/pages/TransactionDetailPage.vue
  src/pages/TransactionsPage.vue
  src/stores/request.ts
Labels: Review effort [1-5]: 3
