Repository traPtitech/Jomon-UI, pull requests merged in 2024-09, with the labels that each got.

#280 dependabot の open-pull-requests-limit を20に
  .github/dependabot.yml
Labels: Review effort [1-5]: 1

#286 feat/dependabot.ymlにグルーピングを追加
  .github/dependabot.yml
Labels: Review effort [1-5]: 1

#288 chore: run npm audit fix
  package-lock.json
Labels: Review effort [1-5]: 1

#289 ♻️ Repository にあったバリデーションを usecase で行う
  src/features/request/repository.ts
  src/features/request/usecase.ts
  src/features/transaction/repository.ts
  src/features/transaction/usecase.ts
Labels: Review effort [1-5]: 2

#290 feat/tailwind に移行する
  package-lock.json
  package.json
  postcss.config.js
  public/mockServiceWorker.js
  src/components/requestDetail/CommentLog.vue
  src/components/requestDetail/RequestContent.vue
  src/components/requests/RequestFilters.vue
  src/components/shared/InputSelectMultiple.vue
  src/components/shared/InputSelectSingle.vue
  src/components/shared/PageLink.vue
  src/components/shared/PaginationBar.vue
  src/components/transactions/TransactionFilters.vue
  src/components/transactions/TransactionItem.vue
  src/main.ts
  src/pages/AdminPage.vue
  src/pages/GroupsPage.vue
  src/pages/NewGroupPage.vue
  src/pages/NewRequestPage.vue
  src/pages/NewTransactionPage.vue
  src/pages/RequestDetailPage.vue
  src/pages/RequestsPage.vue
  src/pages/TransactionsPage.vue
  src/styles/main.css
  tailwind.config.js
  vite.config.ts
  windi.config.ts
Labels: Review effort [1-5]: 3

#295 refactor/typescriptのバージョンを 5.6 にしてfilterの型ガードを消す
  package-lock.json
  package.json
  src/components/shared/InputSelectMultiple.vue
  src/components/transactionDetail/composables/useEditTransation.ts
Labels: Review effort [1-5]: 2

#267 feat/入出金一覧を Figma に合わせる
  src/components/transactions/TransactionFilters.vue
  src/components/transactions/TransactionItem.vue
  src/components/transactions/TransactionTable.vue
  src/pages/TransactionsPage.vue
Labels: Review effort [1-5]: 3

#299 feat/GitHub Actions を月イチで dependabot に掛ける
  .github/dependabot.yml
  .github/release-drafter.yml
Labels: Review effort [1-5]: 2

#268 feat/グループ一覧ページのレイアウトを Figma に揃える
  src/components/groups/GroupItem.vue
  src/components/shared/PaginationBar.vue
  src/pages/GroupsPage.vue
Labels: Review effort [1-5]: 2

#297 feat/入出金リストのレスポンシブ対応
  src/components/shared/TagsGroup.vue
  src/components/transactions/TransactionTable.vue
  src/pages/TransactionsPage.vue
Labels: Review effort [1-5]: 3

#294 feat/グループ詳細のレイアウトを Figma に揃える
  src/components/groupDetail/GroupBudget.vue
  src/components/groupDetail/GroupDescription.vue
  src/components/groupDetail/GroupMembers.vue
  src/components/groupDetail/GroupName.vue
  src/components/groupDetail/GroupOwners.vue
  src/components/shared/InputSelectMultiple.vue
  src/pages/GroupDetailPage.vue
Labels: Review effort [1-5]: 2

#293 feat/グループ新規作成のレイアウトを Figma に揃える
  src/components/shared/InputNumber.vue
  src/components/shared/InputSelectSingle.vue
  src/pages/NewGroupPage.vue
Labels: Review effort [1-5]: 2

#271 feat/admin ページのレイアウトを Figma に揃える
  src/components/shared/InputSelectMultiple.vue
  src/pages/AdminPage.vue
Labels: Review effort [1-5]: 2

#311 feat: dependabotをweeklyに
  .github/dependabot.yml
Labels: Review effort [1-5]: 1

#315 feat: dependabotをmonthlyに
  .github/dependabot.yml
Labels: Review effort [1-5]: 1

#318 ⬆️ chore: run npm ci, npm audit fix
  package-lock.json
  public/mockServiceWorker.js
Labels: Review effort [1-5]: 2
