Repository traPtitech/Jomon-UI, pull requests merged in 2025-06, with the labels that each got.

#446 feat: transactionにtitleを追加
  src/components/transactionDetail/EditTransactionForm.vue
  src/components/transactionDetail/TransactionDetail.vue
  src/components/transactionDetail/composables/useEditTransation.ts
  src/components/transactions/TransactionTable.vue
  src/features/transaction/converter.ts
  src/features/transaction/mock.ts
  src/features/transaction/model.ts
  src/features/transaction/repository.ts
  src/pages/NewTransactionPage.vue
  src/pages/composables/useNewTransaction.ts
Labels: Review effort 3/5

#449 画像の添付・削除の UI を向上
  src/components/newRequest/NewRequestFileForm.vue
Labels: Review effort 2/5

#460 Vue Axe が本番環境に出てることの修正
  src/main.ts
Labels: Review effort 1/5

#459 🎨 フローティングラベルを用いた Input コンポーネントの作成
  src/components/groupDetail/GroupMembers.vue
  src/components/groupDetail/GroupName.vue
  src/components/groupDetail/GroupOwners.vue
  src/components/modal/StatusChangeModal.vue
  src/components/newRequest/NewRequestTag.vue
  src/components/newRequest/NewRequestTargets.vue
  src/components/newTransaction/NewTransactionTarget.vue
  src/components/requestDetail/NewComment.vue
  src/components/requestDetail/RequestContent.vue
  src/components/requestDetail/RequestGroup.vue
  src/components/requestDetail/RequestSidebar.vue
  src/components/requestDetail/RequestTags.vue
  src/components/requestDetail/RequestTarget.vue
  src/components/requestDetail/RequestTitle.vue
  src/components/requests/RequestFilters.vue
  src/components/shared/BaseInput.vue
  src/components/shared/InputNumber.vue
  src/components/shared/InputSelectMultiple.vue
  src/components/shared/InputSelectSingle.vue
  src/components/shared/InputSelectTagWithCreation.vue
  src/components/shared/InputText.vue
  src/components/shared/InputTextarea.vue
  src/components/shared/MarkdownTextarea.vue
  src/components/shared/SearchSelect.vue
  src/components/shared/SearchSelectTag.vue
  src/components/transactionDetail/EditTransactionForm.vue
  src/pages/AdminPage.vue
  src/pages/NewGroupPage.vue
  src/pages/NewRequestPage.vue
  src/pages/NewTransactionPage.vue
  src/pages/RequestDetailPage.vue
Labels: Review effort 4/5

#461 ローカルで建てたバックエンドにアクセスできるようにする
  .env
  .github/workflows/release.yml
  public/mockServiceWorker.js
  src/features/group/usecase.ts
  src/features/request/usecase.ts
  src/features/tag/usecase.ts
  src/features/user/usecase.ts
  src/lib/msw.ts
  src/main.ts
  vite.config.ts
Labels: Review effort 2/5

#467 refactor: group -> partition
  src/components/groupDetail/GroupBudget.vue
  src/components/partitionDetail/PartitionBudget.vue
  src/components/partitionDetail/PartitionName.vue
  src/components/partitionDetail/composables/useDeletePartition.ts
  src/components/partitionDetail/composables/usePartitionInformation.ts
  src/components/partitions/PartitionTable.vue
  src/components/requestDetail/RequestPartition.vue
  src/components/requestDetail/RequestSidebar.vue
  src/components/requestDetail/RequestTags.vue
  src/components/requests/RequestFilters.vue
  src/components/requests/RequestItem.vue
  src/components/shared/TagsPartition.vue
  src/features/group/usecase.ts
  src/features/partition/converter.ts
  src/features/partition/mock.ts
  src/features/partition/model.ts
  src/features/partition/repository.ts
  src/features/partition/usecase.ts
  src/features/request/converter.ts
  src/features/request/mock.ts
  src/features/request/model.ts
  src/lib/msw.ts
  src/pages/NewPartitionPage.vue
  src/pages/NewRequestPage.vue
  src/pages/PartitionDetailPage.vue
  src/pages/PartitionsPage.vue
  src/pages/RequestDetailPage.vue
  src/pages/RequestsPage.vue
  src/pages/composables/useNewGroup.ts
  src/pages/composables/useNewPartition.ts
  src/router.ts
  src/stores/group.ts
  src/stores/groupDetail.ts
  src/stores/partition.ts
  src/stores/partitionDetail.ts
Labels: Review effort 4/5
