Repository traPtitech/Jomon-UI, pull requests merged in 2025-05, with the labels that each got.

#413 chore: update Node.js version to 22.12.0
  .node-version
Labels: dependencies, Review effort 1/5

#190 Feat/request page のデザインを調整
  src/components/requests/RequestItem.vue
  src/components/shared/StatusChip.vue
  src/components/shared/UserIcon.vue
  src/pages/RequestsPage.vue
Labels: Review effort [1-5]: 2

#296 feat/申請詳細ページのファイル周り
  src/components/requestDetail/RequestAttachment.vue
  src/components/requestDetail/RequestContent.vue
  src/pages/RequestDetailPage.vue
Labels: Review effort [1-5]: 3

#417 chore: npm run gen-api
  public/mockServiceWorker.js
  src/lib/apis/generated/api.ts
Labels: Review effort 2/5

#416 fix: ステータスチップのclassの修正
  src/components/shared/StatusChip.vue
Labels: Review effort 2/5

#356 🎸 feat: 全ページ共通のレイアウトとする
  src/App.vue
  src/components/groupDetail/GroupBudget.vue
  src/components/groupDetail/GroupDescription.vue
  src/components/groupDetail/GroupMembers.vue
  src/components/groupDetail/GroupName.vue
  src/components/groupDetail/GroupOwners.vue
  src/components/modal/ModalWrapper.vue
  src/components/modal/StatusChangeModal.vue
  src/components/newRequest/NewRequestFileForm.vue
  src/components/newRequest/NewRequestTag.vue
  src/components/newRequest/NewRequestTargets.vue
  src/components/newTransaction/NewTransactionTarget.vue
  src/components/requestDetail/RequestGroup.vue
  src/components/requestDetail/RequestTags.vue
  src/components/requestDetail/RequestTargets.vue
  src/components/requests/RequestItem.vue
  src/components/shared/InputRadioButton.vue
  src/components/shared/InputSelectSingle.vue
  src/components/transactionDetail/EditTransactionForm.vue
  src/components/transactionDetail/TransactionDetail.vue
  src/pages/AdminPage.vue
  src/pages/GroupDetailPage.vue
  src/pages/GroupsPage.vue
  src/pages/NewGroupPage.vue
  src/pages/NewRequestPage.vue
  src/pages/NewTransactionPage.vue
  src/pages/RequestDetailPage.vue
  src/pages/RequestsPage.vue
  src/pages/TransactionDetailPage.vue
  src/pages/TransactionsPage.vue
Labels: Review effort [1-5]: 4

#361 🎸 feat: a11y に対応した table の作成
  src/components/groups/GroupTable.vue
  src/components/transactions/TransactionTable.vue
  src/pages/GroupsPage.vue
Labels: Review effort [1-5]: 4

#362 🎸 feat: a11y に対応した combobox の作成
  src/components/shared/InputSelectMultiple.vue
  src/components/shared/InputSelectSingle.vue
Labels: Review effort [1-5]: 4

#363 🎸 feat: フォームコントロールに対応するラベルを貼る
  src/pages/AdminPage.vue
  src/pages/NewGroupPage.vue
Labels: Review effort [1-5]: 3

#429 chore: commonワークフローのGITHUB_TOKEN権限を制限
  .github/workflows/common.yml
Labels: Review effort 1/5

#428 chore: add format job to GitHub Actions workflow
  .github/workflows/common.yml
  package.json
Labels: Review effort 2/5

#425 ♿️ ヘッダーに関する a11y の向上
  src/components/modal/ModalWrapper.vue
  src/components/navigation/HeaderButton.vue
  src/components/navigation/JomonHeader.vue
Labels: Review effort 2/5

#430 chore: CIのlintジョブをfixからnofixに修正
  .github/workflows/common.yml
Labels: github_actions, Review effort 1/5

#431 ♿️ 取引画面の a11y を向上
  src/components/transactionDetail/EditTransactionForm.vue
  src/pages/NewTransactionPage.vue
Labels: Review effort 2/5
